name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ssh user@your-vps-ip "cd /path/to/app && git pull && npm install && npm run build && pm2 restart"
